### ISSUE TITLE
VPNService unintended behavior 

### ISSUE THREAD

**Issue by HankAviator** [Demon000/device_xiaomi_sagit#10]
hello, I'm observing an unintended behavior on shadowsocks, a proxy app which works by initiating a VPN connection. A feature of shadowsocks is to choose which apps can be proxied, aka per app proxy. This feature has been working well in all CyanogenMod and LineageOS for bacon, and LineageOS for sagit (xiaobai build). I've tried clearing the data, ART cache and app cache, and currently per app proxy only doesn't work on your build.
Here is an issue description, and the repo owner suggests some investigation in VPNService: https://github.com/shadowsocks/shadowsocks-android/issues/1540

I'm using lineage-14.1-20171130_090058-UNOFFICIAL-sagit.

**Comment by HankAviator** [comment]
Persists in lineage-14.1-20180128

**Comment by HankAviator** [comment]
On xiaobai's build (`lineage-14.1-20171103_081721-UNOFFICIAL-sagit.zip`) there's no such bug, may try to pinpoint commits from 20171022 to 20171130

**Comment by Demon000** [comment]
No logs

**Comment by HankAviator** [comment]
I'd love to capture some logs, but as it may not be a result of dynamic actions, relevant lines may not be present in logcat.
Will be back with log when I flash your build next time. Thx.

**Comment by HankAviator** [comment]
Might be fixed, can't replicate in latest version
